[level:ERROR-file:driver.py-lineno:10] 2023-02-15 19:28:25,261 this is a dummy error in Root
[level:ERROR-file:driver.py-lineno:10] 2023-02-16 16:09:42,362 this is a dummy error in Root
[level:ERROR-file:driver.py-lineno:10] 2023-02-16 16:09:42,362 this is a dummy error in Root
[level:DEBUG-file:driver.py-lineno:17] 2023-02-16 16:09:42,363 I am within the constructor
[level:DEBUG-file:driver.py-lineno:20] 2023-02-16 16:09:42,363 inside my function . Processing csv file
